### ISSUE TITLE
Option to disable gofumpt

### ISSUE THREAD

**Issue by matthewmueller** [hexops/valast#12]
I was wondering if you could provide an option to disable `gofumpt`?

I use valast in tests and calling out to `gofumpt` slows them down quite a bit. I also don't need the newline capabilities, so I'd love to able to turn this off. 

For reference, I'm currently using `valast@1.0.0`. This version is perfect for me right now, but it'd be nice to stay up-to-date.

**Comment by slimsag** [comment]
Hi there!

I'm not sure there is a good reason in practice to allow disabling `gofumpt`, there _has_ to be a formatter which turns the AST into text format; currently this is `go/format` then followed by `gofumpt` but I can envision this _just_ being `gofumpt` soon.

That said, I am eager to figure out why you are seeing it be slow. Have you tried v1.4.0? It contains some massive performance improvements on complex data types: https://github.com/hexops/valast/pull/10

Can you run your tests with `VALAST_PROFILE=true` and upload the profiling dump it prints to stdout? That will tell us where the time is spent

**Comment by matthewmueller** [comment]
Thanks for the comment! I feel slightly embarrassed because for some reason I thought you were using `exec.Command` and spawning a process to format. Maybe in a previous version? I remember upgrading and a while back and it being quite a bit slower. 

Looking at the code now, using gofumpt as a library to print the AST should be pretty fast.

Sorry about that!

**Comment by slimsag** [comment]
Awesome :) And no worries! Also I see @mvdan has been doing some really great work on gofumpt and sending CLs to the upstream Go formatter to make it even faster with support for multi-threading, so I'll be able to pull that in here soon as well!
