### ISSUE TITLE
Bug: Stringifying a struct which contains a pointer to integer yields incorrect results.

### ISSUE THREAD

**Issue by fkautz** [hexops/valast#15]
Stringifying a pointer to integer in a struct yields incorrect results. Here is an example for int64.

### simple use case works
```go
	i64 := int64(3607)
	test_str := String(&i64)
```
yields
```go
valast.Addr(int64(3607)).(*int64)
```

### nested in struct results in invalid output
```go
	i64 := int64(3607)
	got := str{
		ExpirationSeconds: &i64,
	}

	test_str := String(got)
```
yields
```go
valast.str{ExpirationSeconds: valast.Addr(3607).(*int64)}
```

This breaks for other integer types too.

**Comment by slimsag** [comment]
Hi there!

Thanks for reporting this; I'll see if I can investigate what is causing that in the next few weeks. If you want to send a PR (or even just a test case), please feel free to :)

**Comment by slimsag** [comment]
> valast.str

It's odd it prefixes that type with `valast.` - I find that really surprising.
