### ISSUE TITLE
different require lines in go.mod v1.4.0 vs master

### ISSUE THREAD

**Issue by regorov** [hexops/valast#17]
Hello! 
Thanks for you job!

As recommended we include you package by specifying tag:    
`
require ( 
	github.com/hexops/valast v1.4.0
)    
`
but 
`github.com/hexops/valast/go.mod` in the tag v1.4.0 requires:
`mvdan.cc/gofumpt v0.0.0-20210107193838-d24d34e18d44`

the `d24d34e18d44` cannot be found. it seems dependency bug was fixed in the master 
go.mod:
`mvdan.cc/gofumpt v0.1.1`

Could you please release another tag v1.4.x with correct line in go.mod?
Thank you

Regards,
Robert

**Comment by slimsag** [comment]
v1.4.1 has just been released which should fix this, thanks for the report and sorry for the delay in fixing this!
