### ISSUE TITLE
License:  Unknown and 2 other licenses found

### ISSUE THREAD

**Issue by guettli** [hexops/valast#22]
First: Thank you very much for `valast` and `autogolden`!

On the Github start page of `valast` I see:

>  **Unknown and 2 other licenses found**

Could you please make this explicit.

In my current context I must not use GPL code.

**Comment by slimsag** [comment]
Please read the LICENSE file, it is simple and explains. It is MIT and Apache licensed, at your choosing. GitHub's license detector is not safe to rely on.
