### ISSUE TITLE
Unknown License?

### ISSUE THREAD

**Issue by guettli** [hexops/valast#26]
On the Github frontpage of this repo I see:

>  Unknown and 2 other licenses found

"Unknown" looks a bit strange. It would be nice if valast would be without GPL or other viral licenses.

**Comment by emidoots** [comment]
I suggest reading LICENSE files directly. It is very clear and plain: https://github.com/hexops/valast/blob/main/LICENSE

We do not use GPL or viral licenses.

GitHub's license detection is just garbage.
